version: '3.4'

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: ./Dockerfile.red
    ports:
      - '80:5000'

  backend:
    build:
      context: ./backend
      dockerfile: ./Dockerfile.red
    volumes:
      - $HOME/.aws/credentials:/root/.aws/credentials
    ports:
      - '3000:3000'
