name: Frontend Pipeline

on:
  push:

defaults:
  run:
    working-directory: ./frontend

jobs:
  deploy_staging:
    runs-on: ubuntu-20.04
    environment: staging
    concurrency: 1
    steps:
      - uses: actions/checkout@v3

      - name: Test
        run: echo $AWS_ACCESS_KEY_ID
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
